
#ifndef HAXBOARD_BOARD_COMMON_H_
#define HAXBOARD_BOARD_COMMON_H_

// --- UART ---
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART PINOUT_UART_DEVNO
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN PINOUT_UART_TX
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN PINOUT_UART_RX
#endif

// --- LED ---
#ifdef PINOUT_LED_B2
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN PINOUT_LED_B2
#endif
#elif defined(PINOUT_LED_WS2812)
#ifndef PICO_DEFAULT_WS2812_PIN
#define PICO_DEFAULT_WS2812_PIN PINOUT_LED_WS2812
#endif
#endif

// no I2C
#if HAXMODE_DEV_FEATURES
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C PINOUT_DEV_I2C_DEVNO
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN PINOuT_DEV_I2C_SDA
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN PINOuT_DEV_I2C_SCL
#endif
#endif

// --- SPI (using CS2) ---
#ifndef PICO_DEFAULT_SPI
#define PICO_DEFAULT_SPI PINOUT_SPI_DEVNO
#endif
#ifndef PICO_DEFAULT_SPI_SCK_PIN
#define PICO_DEFAULT_SPI_SCK_PIN PINOUT_SPI_SCLK
#endif
#ifndef PICO_DEFAULT_SPI_TX_PIN
#define PICO_DEFAULT_SPI_TX_PIN PINOUT_SPI_COPI
#endif
#ifndef PICO_DEFAULT_SPI_RX_PIN
#define PICO_DEFAULT_SPI_RX_PIN PINOUT_SPI_CIPO
#endif
#ifndef PICO_DEFAULT_SPI_CSN_PIN
#define PICO_DEFAULT_SPI_CSN_PIN PINOUT_SPI_nCS2
#endif

// board always have a B2 (afaik)
#ifndef PICO_RP2040_B0_SUPPORTED
#define PICO_RP2040_B0_SUPPORTED 0
#endif

#endif

